# Generated by Django 4.1.7 on 2023-03-19 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurantsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('number_of_plates', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_mode', models.CharField(choices=[('POS', 'POS'), ('TRANSFER', 'TRANSFER'), ('CASH', 'CASH'), ('DEBT', 'DEBT'), ('COMPLIMENTARY', 'COMPLIMENTARY')], max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurantdebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid', models.BooleanField(default=False)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantSale.restaurantsale')),
            ],
        ),
    ]
